name: Windows RDP via Ngrok

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Ngrok
        run: choco install ngrok -y

      - name: Set Ngrok Authtoken
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Ngrok and get URL
        shell: powershell
        run: |
          Start-Process ngrok -ArgumentList "tcp 3389" -NoNewWindow -PassThru | Out-Null
          Start-Sleep -Seconds 10
          $resp = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
          $url = $resp.tunnels[0].public_url
          Write-Output "Ngrok URL: $url"
          $url | Out-File ngrok_url.txt -Encoding ascii

      - name: Update Ngrok URL to Gist
        shell: powershell
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.MY_GIST_TOKEN }}
        run: |
          $gistId = $env:GIST_ID
          $gistToken = $env:GIST_TOKEN
          $ngrokUrl = Get-Content ngrok_url.txt
          $body = @{
            files = @{ "ngrok_url.txt" = @{ content = $ngrokUrl } }
          } | ConvertTo-Json -Depth 10
          Invoke-RestMethod -Uri "https://api.github.com/gists/$gistId" -Method PATCH -Headers @{Authorization = "token $gistToken"} -Body $body
